GET http://localhost:5000/api/customers

###

GET http://localhost:5000/api/customers?withAddresses=true

###


GET http://localhost:5000/api/customers/2

###


GET http://localhost:5000/api/timebills/3

###


POST http://localhost:5000/api/timebills
Content-Type: application/json

{
  "hoursWorked": 15.5,
  "rate": 325.00,
  "date": "2023-05-05",
  "clientRequested": true,
  "work": "I did a thing...",
  "customerId": 1,
  "employeeId": 1
}
###


GET http://localhost:5000/api/customers/1/timebills

###


GET http://localhost:5000/api/customers/1/timebills/3